-- MySQL Script generated by MySQL Workbench
-- Sun May 18 15:29:41 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema video_pujcovna
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema video_pujcovna
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `video_pujcovna` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `video_pujcovna` ;

-- -----------------------------------------------------
-- Table `video_pujcovna`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `video_pujcovna`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `pasword_hash` VARCHAR(255) NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `role` ENUM('user', 'admin') NOT NULL DEFAULT 'user',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `video_pujcovna`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `video_pujcovna`.`genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `video_pujcovna`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `video_pujcovna`.`movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `release_year` YEAR NULL,
  `rental_rate` DECIMAL(6,2) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `genres_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movies_genres1_idx` (`genres_id`),
  CONSTRAINT `fk_movies_genres1`
    FOREIGN KEY (`genres_id`)
    REFERENCES `video_pujcovna`.`genres` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE=InnoDB;



-- -----------------------------------------------------
-- Table `video_pujcovna`.`copies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `video_pujcovna`.`copies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `copy_number` VARCHAR(45) NULL,
  `status` ENUM('dostupné', 'zapůjčené', 'ztraceno', 'údržba') NULL,
  `movies_id` INT NOT NULL,
  PRIMARY KEY (`id`, `movies_id`),
  UNIQUE INDEX `copy_number_UNIQUE` (`copy_number` ASC),
  INDEX `fk_copies_movies1_idx` (`movies_id` ASC),
  CONSTRAINT `fk_copies_movies1`
    FOREIGN KEY (`movies_id`)
    REFERENCES `video_pujcovna`.`movies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `video_pujcovna`.`rentals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `video_pujcovna`.`rentals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rental_date` DATETIME NOT NULL,
  `due_date` DATETIME NOT NULL,
  `return_date` DATETIME NULL,
  `rental_fee` DECIMAL(6,2) NULL,
  `later_fee` DECIMAL(6,2) NULL,
  `status` ENUM('probíhá', 'vráceno', 'po splatnosti', 'zrušeno') NULL,
  `users_id` INT NOT NULL,
  `copies_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `copies_id`),
  INDEX `fk_rentals_users_idx` (`users_id` ASC),
  INDEX `fk_rentals_copies1_idx` (`copies_id` ASC),
  CONSTRAINT `fk_rentals_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `video_pujcovna`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rentals_copies1`
    FOREIGN KEY (`copies_id`)
    REFERENCES `video_pujcovna`.`copies` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `video_pujcovna`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `video_pujcovna`.`payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(7,2) NULL,
  `method` ENUM('hotově', 'kartou', 'paypal') NULL,
  `payment_date` DATETIME NULL,
  `rentals_id` INT NOT NULL,
  PRIMARY KEY (`id`, `rentals_id`),
  INDEX `fk_payments_rentals1_idx` (`rentals_id` ASC) ,
  CONSTRAINT `fk_payments_rentals1`
    FOREIGN KEY (`rentals_id`)
    REFERENCES `video_pujcovna`.`rentals` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
